# -*- coding: utf-8 -*-
"""gitpy_run_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LfC5ZXCuoVLvzqDIYMI2nflSI9yFaRq7
"""

from openpyxl import load_workbook
from io import BytesIO
import subprocess
import os
import sys

if not os.path.exists('st_py_run_test_1'):
    subprocess.run(['git','clone','https://github.com/shintarotakasaki/st_py_run_test_1.git'])

sys.path.append('st_py_run_test_1')

def main():
    import streamlit as st
    st.title("Streamlitでレポジトリ内のpyを実行")
    after_xl = st.file_uploader("ファイルををアップロードしてください")

    if after_xl is not None:
        file_mime = after_xl.type

        if file_mime == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            file = BytesIO(after_xl.getvalue())
            wb = load_workbook(filename=file)
            sheet = wb.active
            import xl.des
            st.write(f"Sheet title: {sheet.title}")

        elif file_mime=='application/pdf':
            import pdf.des

        else:
            st.write("エクセルファイル(.xlsx)をアップロードしてください")
            st.stop()
