# -*- coding: utf-8 -*-
"""pdf_des

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-AHm99Pl-xq8_T-8jL-WKbKguBdvy3n
"""

import streamlit as st

def main(uploaded_file):
    st.success('これはPDFです')
    # ここにPDFを処理するコードを追加してください
    # 例:
    # from PyPDF2 import PdfReader
    # reader = PdfReader(uploaded_file)
    # number_of_pages = len(reader.pages)
    # st.write(f"PDFのページ数: {number_of_pages}")
    # for page_number in range(number_of_pages):
    #     page = reader.pages[page_number]
    #     text = page.extract_text()
    #     st.write(f"--- ページ {page_number + 1} ---")
    #     st.write(text)

if __name__ == "__main__":
