# -*- coding: utf-8 -*-
"""pdf_des

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-AHm99Pl-xq8_T-8jL-WKbKguBdvy3n
"""

import streamlit as st

st.success('これはpdfです')

if __name__ == "__main__":
    main()