# -*- coding: utf-8 -*-
"""st_run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJQMhSNH9pw4Z8i2Z5-8yp6Uj46OwuKH
"""

import streamlit as st
st.success('実行完了！')
