# -*- coding: utf-8 -*-
"""xl_des

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-AHm99Pl-xq8_T-8jL-WKbKguBdvy3n
"""
import streamlit as st

def main(sheet):
    st.success('これはexcelです')
    
    # ここにexcelを処理するコードを追加してください

if __name__ == "__main__":
